version: '3.8'

services:
  pgdb:
    container_name: pgdb_webapi
    image: postgres:15.4-alpine
    restart: always
    env_file:
      - ./webapi/.env
    environment:
      - ./webapi/.env
    volumes:
      - pgdb:/var/lib/postgresql/data
    ports:
      - "5435:5432"

  redis:
    image: redis
    container_name: redis
    expose:
      - 6379

  django:
    container_name: backend_webapi
    build:
      dockerfile: Dockerfile
      context: .
    image: webapi_backend:latest
    volumes:
      - static_volume:/var/www/webapi/static
      - media_volume:/var/www/webapi/media
    env_file:
      - ./webapi/.env
    expose:
      - 8000
    depends_on:
      - pgdb

  nginx:
    build:
      dockerfile: Dockerfile
      context: ./docker/nginx/
    container_name: nginx_webapi
    image: nginx-webapi:latest
    volumes:
      - static_volume:/var/www/webapi/static
      - media_volume:/var/www/webapi/media
    ports:
      - "8000:80"
    depends_on:
      - django

volumes:
  static_volume:
  media_volume:
  pgdb:
