# Generated by Django 5.0.3 on 2024-03-22 18:45

import django.core.validators
import django.db.models.deletion
import transport.services
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Location',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('zip', models.CharField(help_text='пример: 00000', max_length=5, unique=True, validators=[transport.services.validate_zip])),
                ('lat', models.DecimalField(decimal_places=5, help_text='широта в градусах', max_digits=7, validators=[django.core.validators.MinValueValidator(-90.0), django.core.validators.MaxValueValidator(90.0)], verbose_name='Широта')),
                ('long', models.DecimalField(decimal_places=5, help_text='долгота в градусах', max_digits=8, validators=[django.core.validators.MinValueValidator(-180.0), django.core.validators.MaxValueValidator(180.0)], verbose_name='Долгота')),
                ('state', models.CharField(max_length=100, verbose_name='Штат')),
                ('city', models.CharField(max_length=100, verbose_name='Город')),
            ],
            options={
                'verbose_name': 'Локация',
                'verbose_name_plural': 'Локации',
                'ordering': ['zip'],
            },
        ),
        migrations.CreateModel(
            name='Cargo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('weight', models.IntegerField(validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(1000)], verbose_name='Вес')),
                ('description', models.TextField(max_length=2000, verbose_name='Описание')),
                ('loc_delivery', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='delivery', to='transport.location', to_field='zip', verbose_name='Назначение')),
                ('loc_pick_up', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='pick_up', to='transport.location', to_field='zip', verbose_name='Отправитель')),
            ],
            options={
                'verbose_name': 'Груз',
                'verbose_name_plural': 'Грузы',
                'ordering': ['id', 'loc_pick_up', 'loc_delivery'],
            },
        ),
        migrations.CreateModel(
            name='Car',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('number', models.CharField(max_length=5, unique=True, validators=[transport.services.validate_number], verbose_name='Машина')),
                ('capacity', models.IntegerField(validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(1000)], verbose_name='Грузоподъемность')),
                ('cur_location', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='cars', to='transport.location', to_field='zip', verbose_name='Текущая локация')),
            ],
            options={
                'verbose_name': 'Машина',
                'verbose_name_plural': 'Машины',
                'ordering': ['id', 'cur_location'],
            },
        ),
    ]
