# Generated by Django 5.0.3 on 2024-03-24 11:58

import django.core.validators
import transport.services
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('transport', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='car',
            name='capacity',
            field=models.IntegerField(help_text='от 1 до 1000', validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(1000)], verbose_name='Грузоподъемность'),
        ),
        migrations.AlterField(
            model_name='car',
            name='number',
            field=models.CharField(help_text='Например: 7952D или 5621a', max_length=5, unique=True, validators=[transport.services.validate_number], verbose_name='Машина'),
        ),
    ]
