# Generated by Django 5.0.3 on 2024-03-24 17:56

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('transport', '0002_alter_car_capacity_alter_car_number'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cargo',
            name='description',
            field=models.TextField(default='Описание груза', help_text='не более 2000 знаков', max_length=2000, verbose_name='Описание'),
        ),
        migrations.AlterField(
            model_name='cargo',
            name='weight',
            field=models.IntegerField(default=100, help_text='от 1 до 1000', validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(1000)], verbose_name='Вес'),
        ),
    ]
